### ISSUE TITLE
slurmworkflow issue on EmoryHPC

### ISSUE THREAD

**Issue by smjenness** [EpiModel/BigNets#1]
@AdrienLeGuillou : I merged in some minor changes from main, and then followed the estimation workflow file, and it looks like that workflow is correctly set up. I then scp'ed the workflow files over to EmoryHPC:/projects/epimodel/sjenness/BigNets and then ran the following. It seems like a basic permissions issue in initiating the workflow?

```bash
[sjennes@clogin01 BigNets]$ source workflows/estimation/start_workflow.sh 
dirname: invalid option -- 'b'
Try 'dirname --help' for more information.
basename: missing operand
Try 'basename --help' for more information.
mkdir: cannot create directory ‘/log’: Permission denied
Connection to clogin01.sph.emory.edu closed.
```

**Comment by AdrienLeGuillou** [comment]
It's because you "sourced" the script instead of executing it.

you need to replace:

```
[sjennes@clogin01 BigNets]$ source workflows/estimation/start_workflow.sh 
```

with 

```
[sjennes@clogin01 BigNets]$ workflows/estimation/start_workflow.sh 
```

The script needs to be run as it allows to recover the location of the script with the `dirname $0` command.

I wrote it in the vignette but did not specify that it was not the same thing as sourcing. I will update it

**Comment by AdrienLeGuillou** [comment]
Oh actually it's there already:
https://github.com/EpiModel/EpiModelHPC/blob/main/vignettes/epimodelhiv-slurmworkflow.Rmd#L309

if you have an idea on how to make it clearer I will gladly update it

**Comment by smjenness** [comment]
I understand now. My simple error...
